src/Cobase/AppBundle/Entity/Group.php
<?php

namespace Cobase\AppBundle\Entity;

use Symfomy\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="Cobase\AppBundle\Repository\GroupRepository")
 * @ORM\Table(name="groups")
 * @ORM\HasLifecycleCallbacks()
 * @Gedmo\SoftDeleteable(fieldName="deleted")
 */
class Group
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $shortUrl;

    /**
     * @ORM\Column(type="string")
     */
    protected $title;

    /**
     * @ORM\Column(type="string")
     */
    protected $slug;

    /**
     * @ORM\Column(type="string")
     */
    protected $description;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $tags;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $isPublic;

    /**
     * @ORM\ManyToOne(targetEntity="Cobase\UserBundle\Entity\User", inversedBy="groupsFollowed")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $user;

    /**
     * @ORM\OneToMany(targetEntity="Post", mappedBy="group")
     */
    protected $posts;

    /**
     * @ORM\OneToMany(targetEntity="Subscription", mappedBy="group")
     */
    protected $subscriptions;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="Cobase\AppBundle\Entity\Notification", mappedBy="group")
     */
    protected $notifications;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $created;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $updated;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $deleted;


    public function __construct()
    {
        $this->posts = new ArrayCollection();
        $this->notifications = new ArrayCollection();

        $this->shortUrl = base_convert(microtime(true), 10, 36);
        $this->setCreated(new \DateTime());
        $this->setUpdated(new \DateTime());
        $this->setIsPublic(true);
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedValue()
    {
        $this->setCreated(new \DateTime());
        $this->setUpdated(new \DateTime());
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedValue()
    {
        $this->setUpdated(new \DateTime());
    }

    public function __toString()
    {
        return $this->getTitle();
    }

    /**
     * Generate slugified version of given string
     *
     * @param $text
     * @return mixed|string
     */
    public function slugify($text)
    {
        // replace non letter or digits by -
        $text = preg_replace('#[^\\pL\d]+#u', '-', $text);

        // trim
        $text = trim($text, '-');

        // transliterate
        if (function_exists('iconv'))
        {
            $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
        }

        // lowercase
        $text = strtolower($text);

        // remove unwanted characters
        $text = preg_replace('#[^-\w]+#', '', $text);

        if (empty($text))
        {
            return 'n-a';
        }

        return $text;
    }

    /**
     * Create short URL
     */
    public function createShortUrl()
    {
        $this->shortUrl = base_convert(microtime(true), 10, 36);
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get group's short URL
     *
     * @return string
     */
    public function getShortUrl()
    {
        return $this->shortUrl;
    }

    /**
     * Set title
     *
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;

        $this->setSlug($this->title);
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param text $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * Get description
     *
     * @return text
     */
    public function getDescription($length = null)
    {
        if (false === is_null($length) && $length > 0)
            return substr($this->description, 0, $length);
        else
            return $this->description;
    }

    /**
     * Set tags
     *
     * @param text $tags
     */
    public function setTags($tags)
    {
        $this->tags = $tags;
    }

    /**
     * Get tags
     *
     * @return text
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Set public state
     *
     * @param boolean $isPublic
     */
    public function setIsPublic($isPublic)
    {
        $this->isPublic = $isPublic;
    }

    /**
     * Get public state
     *
     * @return boolean
     */
    public function getIsPublic()
    {
        return $this->isPublic;
    }

    /**
     * Set public state
     *
     * @param Cobase\UserBundle\Entity\User $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * Get public state
     *
     * @return Cobase\UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Get posts
     *
     * @return Doctrine\Common\Collections\Collection
     */
    public function getPosts()
    {
        return $this->posts;
    }

    /**
     * Return count of posts
     *
     * @return integer
     */
    public function getCountPosts()
    {
        return count($this->posts);
    }

    /**
     * Set created
     *
     * @param datetime $created
     */
    public function setCreated($created)
    {
        $this->created = $created;
    }

    /**
     * Get created
     *
     * @return datetime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param datetime $updated
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;
    }

    /**
     * Get updated
     *
     * @return datetime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set deleted
     *
     * @param datetime $deleted
     */
    public function setDeleted($deleted)
    {
        $this->deleted = $deleted;
    }

    /**
     * Get deleted
     *
     * @return datetime
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * Set slug
     *
     * @param string $slug
     */
    public function setSlug($slug)
    {
        $this->slug = $this->slugify($slug);
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param Notification $notification
     * @return Group
     */
    public function addNotification(Notification $notification)
    {
        if ($this->notifications->contains($notification)) {
            $this->notifications->add($notification);
            $notification->setGroup($this);
        }

        return $this;
    }

    /**
     * @param Notification $notification
     * @return Group
     */
    public function removeNotification(Notification $notification)
    {
        if ($this->notifications->contains($notification)) {
            $this->notifications->removeElement($notification);
            $notification->setGroup(null);
        }

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getNotifications()
    {
        return $this->notifications;
    }
}

src/Cobase/AppBundle/Resources/views/Page/about.tab.html.twig
<ul class="cards">
    <li style="padding: 0em 1em;"><h3>About this application</h3></li>
    <li>This application serves as a social media for corporations. It allows people within a corporation to spread information to collegues in a modern and sophisticated way. No more sending emails to the whole company and problems with messages disappearing in the mass of data pollution.</li>
    <li>A group consists of its own page in which people can write updates about things related to that specific group. All new messages are rendered at the top of group's page.</li>
    <li>To prevent situation of being flooded with information that is not interesting to a particular user, each user can subscribe to a group. Only those posts from the groups that user is subscribed to will be shown on front page from newest post to the oldest..</li>
    <li>User profile photo is maintained by an external service <a href="http://www.gravatar.com" target="BLANK">Gravatar</a>. It allows you to set a specific avatar for your email and can be used in many 3rd party applications such as this and Wordpress. Once you create a gravatar with the email address used in this application, an avatar will appear next to your posts.</li>
</ul>

src/Cobase/AppBundle/Resources/views/Page/allEvents.html.twig
{% extends 'CobaseAppBundle::layout.html.twig' %}

{% block content %}
    <h2 class="p8" xmlns="http://www.w3.org/1999/html"><span class="color-1">Browse</span> all events</h2>
    {% for event in events %}
        <article class="event">
            <div class="author">
                <a href="{{ path('CobaseAppBundle_event_view', { 'eventId': event.shortUrl }) }}"><img src="{{ gravatar(event.user.getEmail()) }}"/></a>
            </div>
            <div class="data">
                <header>
                    <h3><a href="{{ path('CobaseAppBundle_event_view', { 'eventId': event.shortUrl }) }}">{{ event.title }}</a></h3>
                    {{ event.created|date('M d, Y') }} by <a href="{{ path('CobaseAppBundle_cv') }}/{{ event.user.getUserName() }}">{{ event.user.getName() }}</a>
                </header>
                <p class="description">{{ event.description|show_maxlen(65, '...') }}</p>
                <p class="count"><img src="{{ asset('images/hand.gif') }}"/>{{ event.countHighfives }} high fives</p>
            </div>
        </article>
    {% else %}
        <p class="p2"><strong>No events found...</strong></p>
    {% endfor %}
{% endblock content %}

{% block sidenav %}



    <h2 class="p3"><span class="color-1">Sorting</span> options</h2>
    <ul class="list-1">
        <li><a href="{{ path('CobaseAppBundle_all_events') }}/title/asc">Events A-Z</a></li>
        <li><a href="{{ path('CobaseAppBundle_all_events') }}/title/desc">Events Z-A</a></li>
        <li><a href="{{ path('CobaseAppBundle_all_events') }}/created/desc">Latest events</a></li>
        <li><a href="{{ path('CobaseAppBundle_all_events') }}/created/asc">Oldest events</a></li>
    </ul>
    <br/>

    <h2 class="p3"><span class="color-1">Show</span> me</h2>
    <ul class="list-1">
        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
            <li><a href="{{ path('CobaseAppBundle_highfives_received') }}">Latest for you</a></li>
        {% endif %}
        <li><a href="{{ path('CobaseAppBundle_all_events') }}">All events</a></li>
        <li><a href="{{ path('CobaseAppBundle_all_highFives') }}">All high fives</a></li>
        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
            <li><a href="{{ path('CobaseAppBundle_all_quickHighFives') }}">All quickies for you</a></li>
        {% endif %}
        <li><a href="{{ path('CobaseAppBundle_users') }}">All users</a></li>
    </ul>

    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
        <br/>
        <h2 class="p3"><span class="color-1">Your</span> options</h2>
        <ul class="list-1">
            <li><a href="{{ path('CobaseAppBundle_event_new') }}">Create new event</a></li>
            <li><a href="{{ path('CobaseAppBundle_cv') }}">Activity page</a></li>
        </ul>
    {% endif %}

    <!-- functinality not implemented yet
    <div class="form-search">
        <h2><span class="color-1 editable">Find </span>a user</h2>
        <form id="form-user-search" method="post">
            <input id="search-user-keyword" type="text" value="Enter username" onBlur="if(this.value=='') this.value='Enter username'" onFocus="if(this.value =='Enter username' ) this.value=''"  />
            <a id="user-search-submit" href="#" onClick="document.getElementById('form-search').submit()" class="search_button">Search</a>
        </form>
    </div>
    -->

    <div class="form-search">
        <h2><span class="color-1 editable">Find </span>an event</h2>
        <form id="form-event-search" method="post">
            <input id="search-event-keyword" name="searchWord" type="text" />
            <input id="event-search-submit" type="submit" class="search_button" value="Search">
        </form>
    </div>

    <div class="addThis">
        <h2 class="p3"><span class="color-1">Share</span> with friends</h2>
        <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
            <a class="addthis_button_facebook at300b" original-title="Facebook" href="#">
                <span class=" at300bs at15nc at15t_facebook">
                    <span class="at_a11y">Share on facebook</span>
                </span>
            </a>
            <a class="addthis_button_linkedin at300b" original-title="Linkedin" href="http://www.addthis.com/bookmark.php?v=250&amp;winname=addthis&amp;pub=xa-4f38d9fc271a9537&amp;source=tbx32-250&amp;lng=en-US&amp;s=linkedin&amp;url=http%3A%2F%2Fsykettatyohon.fi%2Ffi&amp;title=Etusivu-%20Ty%C3%B6hyvinvoinnin%20kohtaamispaikka&amp;ate=AT-xa-4f38d9fc271a9537/-/-/50b4cd2fb0ad546b/2&amp;frommenu=1&amp;uid=50b4cd2fa7d7a0d7&amp;ct=1&amp;pre=http%3A%2F%2Fwww.google.fi%2Furl%3Fsa%3Dt%26rct%3Dj%26q%3D%26esrc%3Ds%26source%3Dweb%26cd%3D1%26ved%3D0CCgQFjAA%26url%3Dhttp%253A%252F%252Fsykettatyohon.fi%252F%26ei%3DLM20UIPULMnk4QS_6oHQCg%26usg%3DAFQjCNEvexbdIpwKXJ3wjbqHzz2gkB-rxg&amp;tt=0&amp;captcha_provider=nucaptcha" target="_blank">
                <span class=" at300bs at15nc at15t_linkedin">
                    <span class="at_a11y">Share on linkedin</span>
                </span>
            </a>
            <a class="addthis_button_twitter at300b" original-title="Tweet This" href="#">
                <span class=" at300bs at15nc at15t_twitter">
                    <span class="at_a11y">Share on twitter</span>
                </span>
            </a>
            <a class="addthis_button_compact at300m" href="#">
                <span class=" at300bs at15nc at15t_compact">
                    <span class="at_a11y">More Sharing Services</span>
                </span>
            </a>
            <div class="atclear"></div>
        </div>
        <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f38d9fc271a9537"></script>
        <!-- AddThis Button END -->
    </div>
{% endblock sidenav %}

src/Cobase/AppBundle/Resources/views/Page/allGroups.html.twig
{% extends 'CobaseAppBundle::layout.html.twig' %}

{% block dynamic_javascripts %}
    var groupId = null;

    var deletes = {
        state0: {
            title: 'Delete Group',
            html:'<label>Are you sure you want to delete this group?</label>',
            buttons: { OK: 1 },
            focus: 1,
            submit:function(e,v,m,f){
                e.preventDefault();
                
                var data = {};
                data["groupId"] = groupId;
            
                // fire off the request
                request = $.ajax({
                    url: "{{ path('CobaseAppBundle_group_delete')}}",
                    type: "post",
                    data: data
                });
            
                // callback handler that will be called on success
                request.done(function (response, textStatus, jqXHR){
                    var data = jQuery.parseJSON(response);
                    window.location.href = data.url;
                });
            
                // callback handler that will be called on failure
                request.fail(function (jqXHR, textStatus, errorThrown){
                    alert("An error occured. Could not delete group.");
                });
            
                if(v==1) $.prompt.close();
                if(v==-1) $.prompt.goToState('state0');
            }
        },
    };

    $( ".delete-group-link" )
        .click(function(e) {
            e.preventDefault();
            groupId = $(this).attr("data-group-id");
            $.prompt(deletes);
    });
{% endblock %}

{% block content %}
<div class="row-fluid">

    {% if not is_granted("IS_AUTHENTICATED_REMEMBERED") %}
        <div class="attention-catcher shadow-below">
            <h2>Please login or register an account</h2>
            <p>
                In order to access many great features on this site, you need to
                {% if allow_registration %}
                    either <a href="{{ path('fos_user_security_login') }}">login</a> or <a href="{{ path('fos_user_registration_register') }}">register</a> an account.
                {% else %}
                    <a href="{{ path('fos_user_security_login') }}">login</a> with your user account.
                {% endif %}
            </p>
        </div>
    {% endif %}

    <h2>Browse all groups</h2>

    {% for flashMessage in app.session.flashbag.get('group.message') %}
        <div class="alert alert-success fade in">
            {{ flashMessage|raw }}
        </div>
    {% endfor %}

    {# total items count #}
    <div class="count-stats">
        Total of {{ pagination.getTotalItemCount }} groups found.
    </div>
    
    <ul class="item-summary">
        {% for group in pagination %}
            <li>
                <div class="overview">
                    <p class="main-detail">{{ group.created|date('M d') }}</p>
                    <p class="main-detail">{{ group.created|date('Y') }}</p>
                    <p class="sub-detail">at {{ group.created|date('H:i') }}</p>
                    {{ group.created|show_newflag|raw }}
                </div>
                <div class="info">
                    <p class="group-title"><a href="{{ path('CobaseAppBundle_group_view', { 'groupId': group.shortUrl }) }}">{{ group.title }}</a></p>
                    <p class="group-description">{{ group.description }}</p>
                    <p class="group-option-links">
                        <a class="btn btn-mini group-subscribe" href="{{ path('CobaseAppBundle_group_view', { 'groupId': group.shortUrl }) }}"><i class="icon-eye-open"></i> View {{ group.countPosts }} post(s)</a>
                        {% if is_granted('EDIT', group) or is_granted('ROLE_ADMIN') %}
                            <a class="btn btn-mini edit-group-link" href="{{ path('CobaseAppBundle_group_modify', { 'groupId': group.shortUrl }) }}"><i class="icon-edit"></i> Edit</a>
                            <a class="btn btn-mini delete-group-link" href="{{ path('CobaseAppBundle_group_delete') }}" data-group-id="{{ group.shortUrl }}"><i class="icon-remove"></i> Delete</a>
                        {% endif %}
                    </p>
                </div>
                <div class="clearfix"></div>
            </li>
        {% else %}
            <p class="no-data">
                Currently there are no groups created.
                {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                    Perhaps you could create one now?
                {% else %}
                    Please login and come back to create one.
                {% endif %}
            </p>
        {% endfor %}
    </ul>

    {# display navigation #}
    <div class="navigation">
        {{ knp_pagination_render(pagination, 'CobaseAppBundle:Common:default.pagination.html.twig') }}
    </div>
</div>
{% endblock content %}

src/Cobase/AppBundle/Resources/views/Page/allQuickHighFives.html.twig
{% extends 'CobaseAppBundle::layout.html.twig' %}

{% block content %}
    <h2 class="p10"><span class="color-1">Browse</span> all quick high fives <span class="color-1">for you</span></h2>
    {% for quickHighfive in quickHighfives %}
        <article class="event">
            <div class="data">
                <header>
                    {{ quickHighfive.created|date('M d, Y') }} by <a href="#">{{ quickHighfive.getAuthor() }}</a>
                </header>
                <p class="description">{{ quickHighfive.comment }}</p>
            </div>
        </article>
    {% else %}
        <p class="p2"><strong>No quick high fives found...</strong></p>
    {% endfor %}
{% endblock content %}

{% block sidenav %}
    <h2 class="p3"><span class="color-1">Sorting</span> options</h2>
    <ul class="list-1">
        <li><a href="{{ path('CobaseAppBundle_all_quickHighFives') }}/desc">Latest quickies</a></li>
        <li><a href="{{ path('CobaseAppBundle_all_quickHighFives') }}/asc">Oldest quickies</a></li>
    </ul>
    <br/>

    <h2 class="p3"><span class="color-1">Show</span> me</h2>
    <ul class="list-1">
        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
            <li><a href="{{ path('CobaseAppBundle_highfives_received') }}">Latest for you</a></li>
        {% endif %}
        <li><a href="{{ path('CobaseAppBundle_all_events') }}">All events</a></li>
        <li><a href="{{ path('CobaseAppBundle_all_highFives') }}">All high fives</a></li>
        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
            <li><a href="{{ path('CobaseAppBundle_all_quickHighFives') }}">All quickies for you</a></li>
        {% endif %}
        <li><a href="{{ path('CobaseAppBundle_users') }}">All users</a></li>
    </ul>

    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
        <br/>
        <h2 class="p3"><span class="color-1">Your</span> options</h2>
        <ul class="list-1">
            <li><a href="{{ path('CobaseAppBundle_event_new') }}">Create new event</a></li>
            <li><a href="{{ path('CobaseAppBundle_cv') }}">Activity page</a></li>
        </ul>
    {% endif %}

    <!-- functinality not implemented yet
    <div class="form-search">
        <h2><span class="color-1 editable">Find </span>a user</h2>
        <form id="form-user-search" method="post">
            <input id="search-user-keyword" type="text" value="Enter username" onBlur="if(this.value=='') this.value='Enter username'" onFocus="if(this.value =='Enter username' ) this.value=''"  />
            <a id="user-search-submit" href="#" onClick="document.getElementById('form-search').submit()" class="search_button">Search</a>
        </form>
    </div>
    -->

    <div class="form-search">
        <h2><span class="color-1 editable">Find </span>an event</h2>
        <form id="form-event-search" method="post">
            <input id="search-event-keyword" name="searchWord" type="text" />
            <input id="event-search-submit" type="submit" class="search_button" value="Search">
        </form>
    </div>

    <div class="addThis">
        <h2 class="p3"><span class="color-1">Share</span> with friends</h2>
        <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
            <a class="addthis_button_facebook at300b" original-title="Facebook" href="#">
                <span class=" at300bs at15nc at15t_facebook">
                    <span class="at_a11y">Share on facebook</span>
                </span>
            </a>
            <a class="addthis_button_linkedin at300b" original-title="Linkedin" href="http://www.addthis.com/bookmark.php?v=250&amp;winname=addthis&amp;pub=xa-4f38d9fc271a9537&amp;source=tbx32-250&amp;lng=en-US&amp;s=linkedin&amp;url=http%3A%2F%2Fsykettatyohon.fi%2Ffi&amp;title=Etusivu-%20Ty%C3%B6hyvinvoinnin%20kohtaamispaikka&amp;ate=AT-xa-4f38d9fc271a9537/-/-/50b4cd2fb0ad546b/2&amp;frommenu=1&amp;uid=50b4cd2fa7d7a0d7&amp;ct=1&amp;pre=http%3A%2F%2Fwww.google.fi%2Furl%3Fsa%3Dt%26rct%3Dj%26q%3D%26esrc%3Ds%26source%3Dweb%26cd%3D1%26ved%3D0CCgQFjAA%26url%3Dhttp%253A%252F%252Fsykettatyohon.fi%252F%26ei%3DLM20UIPULMnk4QS_6oHQCg%26usg%3DAFQjCNEvexbdIpwKXJ3wjbqHzz2gkB-rxg&amp;tt=0&amp;captcha_provider=nucaptcha" target="_blank">
                <span class=" at300bs at15nc at15t_linkedin">
                    <span class="at_a11y">Share on linkedin</span>
                </span>
            </a>
            <a class="addthis_button_twitter at300b" original-title="Tweet This" href="#">
                <span class=" at300bs at15nc at15t_twitter">
                    <span class="at_a11y">Share on twitter</span>
                </span>
            </a>
            <a class="addthis_button_compact at300m" href="#">
                <span class=" at300bs at15nc at15t_compact">
                    <span class="at_a11y">More Sharing Services</span>
                </span>
            </a>
            <div class="atclear"></div>
        </div>
        <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4f38d9fc271a9537"></script>
        <!-- AddThis Button END -->
    </div>
{% endblock sidenav %}

src/Cobase/AppBundle/Resources/views/Page/latestGroups.tab.html.twig
<ul class="cards">
    <li style="padding: 0em 1em;">
        <h3>Latest Groups</h3>
    </li>
    {% for group in latestGroups if latestGroups != null %}
        <li class="latestGroupItem">
            <h5><a href="{{ path('CobaseAppBundle_group_view', { 'groupId': group.shortUrl }) }}">{{ group.title }}</a></h5>
            <p>{{ group.description }}</p>
            <p>{{ group.posts|length }} post(s)</p>
        </li>
    {% endfor %}
</ul>

src/Cobase/AppBundle/Resources/views/Page/latestUsers.tab.html.twig
<ul class="cards">
    <li style="padding: 0em 1em;"><h3>Latest Users</h3></li>
    {% for user in latestUsers if latestUsers != null %}
        <li>
            {% if user.avatar %}
                <img class="latest-users-gravatar" style="max-width: 50px" src="{{ path('CobaseAppBundle_avatar', {'avatarFile': user.avatar}) }}"/>
            {% else %}
                <img class="latest-users-gravatar" src="{{ gravatar(user.email, 50) }}"/>
            {% endif %}

            <p><a href="{{ path('CobaseAppBundle_user_view', { 'username': user.username }) }}">{{ user.name }}</a></p>
            <p>{% if user.emailVisible %}{{ user.email }}{% endif %}</p>
        </li>
    {% endfor %}
</ul>

src/Cobase/AppBundle/Resources/views/Page/newPostEmail.txt.twig
Hello!

This email is to inform you that someone has posted to group '{{ group.title }}'.

You can check the new post at http://www.cobase.com{{ path('CobaseAppBundle_group_view', { 'groupId': group.shortUrl }) }}

Sincerely,

Cobase Crew